### ISSUE TITLE
icon.png appears to be corrupted

### ISSUE THREAD

**Issue by unilock** [StellarWitch7/libstellar#1]
The mod's icon ([icon.png](https://github.com/StellarWitch7/libstellar/blob/5f3a35c134e218173c73cfacedcf6a3be929d8d2/src/main/resources/assets/libstellar/icon.png)) appears to be corrupt.

This is what macOS's preview displays for it:

<img width="410" alt="image" src="https://github.com/user-attachments/assets/7e2b3dd4-9c70-47cc-8a67-3c9f3b5f2d13">

GitHub's preview doesn't work at all...

<img width="1280" alt="image" src="https://github.com/user-attachments/assets/d827f486-3f0f-488a-97ec-fc8c2b418cac">

This can cause mods that make use of mod icons, such as [Catalogue](https://legacy.curseforge.com/minecraft/mc-mods/catalogue), to experience issues, or even crash the game.

**Comment by aurakle** [comment]
Oh wow... I've no idea how that's happened. Thanks for letting me know.

**Comment by aurakle** [comment]
Fixed in 2.0.2!
